[versions]
accompanist = "0.34.0"
accompanistSwipeRefresh = '0.27.0'
androidDesugarJdkLibs = "2.0.4"
androidGradlePlugin = "8.4.2"
androidTools = "31.5.0"
androidxActivity = "1.9.0"
androidxAppCompat = "1.7.0"
androidxComposeBom = "2024.06.00"
androidxComposeUi = "1.7.0-beta03"
androidxComposeUiTest = "1.7.0-beta04"
androidxComposeRuntime = "1.7.0-beta03"
androidxComposeRuntimeTracing = "1.0.0-beta01"
androidxComposeMaterial3 = "1.3.0-beta03"
androidxCore = "1.13.1"
androidxCoreSplashscreen = "1.0.1"
androidxEspresso = "3.5.1"
androidxHiltNavigationCompose = "1.2.0"
androidxLifecycle = "2.8.2"
androidxMacroBenchmark = "1.2.4"
androidxMetrics = "1.0.0-beta01"
androidxNavigation = "2.7.7"
androidxProfileinstaller = "1.3.1"
androidxTestCore = "1.5.0"
androidxTestExt = "1.1.5"
androidxTestRules = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTracing = "1.2.0"
androidxUiAutomator = "2.3.0"
androidxWindowManager = "1.3.0"
androidxDataStore = "1.1.1"
androidxWork = "2.9.0"
coil = "2.6.0"
dependencyGuard = "0.5.0"
exyte-navigation = '1.0.0'
firebaseBom = "33.1.0"
firebaseCrashlyticsPlugin = "3.0.1"
firebasePerfPlugin = "1.4.2"
gmsPlugin = "4.4.2"
googleOss = "17.1.0"
googleOssPlugin = "0.10.6"
hilt = "2.51.1"
hiltExt = "1.2.0"
jacoco = "0.8.7"
junit = "1.1.5"
kotlin = "2.0.0"
kotlinxCoroutines = "1.8.1"
kotlinxDatetime = "0.5.0"
kotlinxSerializationJson = "1.6.3"
kotlinxImmutable = "0.3.6"
ksp = "2.0.0-1.0.22"
lottieVersion = "6.4.0"
moduleGraph = "2.5.0"
moshiVersion = '1.15.1'
posPrinterVersion = '3.4.0'
protobuf = "4.26.0"
protobufPlugin = "0.9.4"
playScanner = "16.1.0"
playService = "18.5.0"
revealswipeVersion = '1.1.0'
raamcostaVersion = "1.9.56"
room = "2.6.1"
robolectric = "4.11.1"
roborazzi = "1.20.0"
secrets = "2.0.1"
sentryVersion = '4.6.0'
sentryAndroidVersion = '7.9.0'
turbine = "1.1.0"
timberVersion = '5.0.1'
vanpraComposeVersion = '0.9.0'
zxing = "3.5.1"
saketSwipe = "1.2.0"
konfetti-compose = "2.0.4"
compiler-report = "1.3.1"

# App Version
namespace = "com.niyaj.poposroom"
minSdk = "26"
compileSdk = "34"
targetSdk = "34"
versionCode = "1"
versionName = "1.0.7"

[libraries]
# Accompanist library
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanistSwipeRefresh" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# AndroidX Libraries
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
# Androidx Activity Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-benchmark-macro = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidxMacroBenchmark" }

# Androidx Compose UI
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }

# Androidx Compose Material
androidx-compose-material-iconsExtended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidxComposeMaterial3" }

# Androidx Compose Runtime
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "androidxComposeRuntime" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidxComposeRuntimeTracing" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "androidxComposeUi" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "androidxComposeUiTest" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util", version.ref = "androidxComposeUi" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "androidxComposeUi" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore", version.ref = "androidxDataStore" }

# Androidx Startup and Splash Screen
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }

# Androidx Hilt Navigation
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }

# Androidx Lifecycle
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }

androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidxMetrics" }

# Androidx Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }

androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileinstaller" }

androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }
androidx-window-manager = { module = "androidx.window:window", version.ref = "androidxWindowManager" }
androidx-window-core = { group = "androidx.window", name = "window-core", version.ref = "androidxWindowManager" }

# Androidx Work
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }

coil-kt = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

# Compose Material Dialogs
dialog-core = { group = "io.github.vanpra.compose-material-dialogs", name = "core", version.ref = "vanpraComposeVersion" }
dialog-datetime = { group = "io.github.vanpra.compose-material-dialogs", name = "datetime", version.ref = "vanpraComposeVersion" }

# Firebase Analytics & Bom
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }

# Google OSS Plugins
google-oss-licenses = { group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "googleOss" }
google-oss-licenses-plugin = { group = "com.google.android.gms", name = "oss-licenses-plugin", version.ref = "googleOssPlugin" }

# Hilt.
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }

javax-inject = { module = "javax.inject:javax.inject", version = "1" }

# Coroutines
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
# For testing
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinx-collections-immutable = {group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable"}

konfetti-compose = { group = "nl.dionsegijn", name = "konfetti-compose", version.ref = "konfetti-compose" }

lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "androidTools" }
lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "androidTools" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "androidTools" }

lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieVersion" }

# Moshi
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshiVersion" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshiVersion" }

# Exyte Animated Bottom Navigation
navigation-bar = { group = "com.exyte", name = "animated-navigation-bar", version.ref = "exyte-navigation"}

# Pos-printer
pos-printer = { group = "com.github.DantSu", name = "ESCPOS-ThermalPrinter-Android", version.ref = "posPrinterVersion" }

#Google Play
play-gms-scanner = { group = "com.google.android.gms", name = "play-services-code-scanner", version.ref = "playScanner"}
play-service = {group = "com.google.android.gms", name = "play-services-base", version.ref = "playService"}

#Protobuf
protobuf-kotlin-lite = { group = "com.google.protobuf", name = "protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-protoc = { group = "com.google.protobuf", name = "protoc", version.ref = "protobuf" }

# Room Database
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }

robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }

# RevealSwipe
revealswipe = { group = "de.charlex.compose", name = "revealswipe", version.ref = "revealswipeVersion" }

# RamCosta Library
raamcosta-animation-core = { group = "io.github.raamcosta.compose-destinations", name = "animations-core", version.ref = "raamcostaVersion" }
raamcosta-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "raamcostaVersion" }

# Sentry
sentry-android = { group = "io.sentry", name = "sentry-android", version.ref = "sentryAndroidVersion" }
sentry-compose-android = { group = "io.sentry", name = "sentry-compose-android", version.ref = "sentryAndroidVersion" }

turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# Timber
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }

# zxing core & zxing-android-embedded
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing"}

#Saket Swipe To Dismiss
saket-swipe = { group = "me.saket.swipe", name = "swipe", version.ref = "saketSwipe"}

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
compose-gradlePlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
hilt-gradlePlugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
androidx-baselineprofile = { id = "androidx.baselineprofile", version.ref = "androidxMacroBenchmark" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }
gms = { id = "com.google.gms.google-services", version.ref = "gmsPlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
module-graph = { id = "com.jraska.module.graph.assertion", version.ref = "moduleGraph" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
room = { id = "androidx.room", version.ref = "room" }
sentry = { id = "io.sentry.android.gradle", version.ref = "sentryVersion" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
compiler-report = { id = "dev.shreyaspatil.compose-compiler-report-generator", version.ref = "compiler-report"}


# Plugins defined by this project
popos-android-application = { id = "popos.android.application", version = "unspecified" }
popos-android-application-compose = { id = "popos.android.application.compose", version = "unspecified" }
popos-android-application-firebase = { id = "popos.android.application.firebase", version = "unspecified" }
popos-android-application-flavors = { id = "popos.android.application.flavors", version = "unspecified" }
popos-android-application-jacoco = { id = "popos.android.application.jacoco", version = "unspecified" }
popos-android-feature = { id = "popos.android.feature", version = "unspecified" }
popos-android-hilt = { id = "popos.android.hilt", version = "unspecified" }
popos-android-library = { id = "popos.android.library", version = "unspecified" }
popos-android-library-compose = { id = "popos.android.library.compose", version = "unspecified" }
popos-android-library-jacoco = { id = "popos.android.library.jacoco", version = "unspecified" }
popos-android-lint = { id = "popos.android.lint", version = "unspecified" }
popos-android-room = { id = "popos.android.room", version = "unspecified" }
popos-android-test = { id = "popos.android.test", version = "unspecified" }
popos-jvm-library = { id = "popos.jvm.library", version = "unspecified" }